CREATE TABLE IF NOT EXISTS User_upgrades (
    UserUpgradeID INT PRIMARY KEY AUTO_INCREMENT,
    UpgradeName VARCHAR(100) NOT NULL,
    UserID INT,
    BuyDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);