CREATE TABLE IF NOT EXISTS User_upgrades (
    UserUpgradeID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT,
    Upgrade1 BOOLEAN DEFAULT FALSE,
    Upgrade2 BOOLEAN DEFAULT FALSE,
    Upgrade3 BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);