CREATE TABLE IF NOT EXISTS User_buildings (
    UserBuildingID INT PRIMARY KEY AUTO_INCREMENT,
    BuildingName VARCHAR(100) NOT NULL,
    Count INT DEFAULT 0,
    UserID INT,
    BuyDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);