CREATE TABLE IF NOT EXISTS Clans (
    ClanID INT PRIMARY KEY AUTO_INCREMENT,
    ClanName VARCHAR(255) NOT NULL,
    ClanTag VARCHAR(10) NOT NULL,
    ClanDescription VARCHAR(500),
    ClanLeaderID INT,
    CreationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ClanLeaderID) REFERENCES Users(UserID)
);