CREATE TABLE IF NOT EXISTS User_quests (
    UserQuestID INT PRIMARY KEY AUTO_INCREMENT,
    QuestID INT,
    UserID INT,
    CompletionDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (QuestID) REFERENCES Quests(QuestID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);