CREATE TABLE IF NOT EXISTS Users (
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    Carrots INT DEFAULT 0,
    HorseShoes INT DEFAULT 0,
    G_Carrots INT DEFAULT 0,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS User_upgrades (
    UserUpgradeID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT,
    Upgrade1 BOOLEAN DEFAULT FALSE,
    Upgrade2 BOOLEAN DEFAULT FALSE,
    Upgrade3 BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);